# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/ACB1-676B";
  #     fsType = "vfat";
  #     options = [ "fmask=0177" "dmask=0077" "noexec" "nosuid" "nodev" ];
  #   };

  # fileSystems."/nix" =
  #   { device = "/dev/disk/by-uuid/944427b2-861e-464d-af3c-e8da014483bd";
  #     fsType = "btrfs";
  #     options = [ "subvol=@nix" ];
  #   };

  # fileSystems."/persistent" =
  #   { device = "/dev/disk/by-uuid/944427b2-861e-464d-af3c-e8da014483bd";
  #     fsType = "btrfs";
  #     options = [ "subvol=@persistent" ];
  #   };

  # fileSystems."/snapshots" =
  #   { device = "/dev/disk/by-uuid/944427b2-861e-464d-af3c-e8da014483bd";
  #     fsType = "btrfs";
  #     options = [ "subvol=@snapshots" ];
  #   };

  # fileSystems."/tmp" =
  #   { device = "/dev/disk/by-uuid/944427b2-861e-464d-af3c-e8da014483bd";
  #     fsType = "btrfs";
  #     options = [ "subvol=@tmp" ];
  #   };

  # fileSystems."/btr_pool" =
  #   { device = "/dev/disk/by-uuid/944427b2-861e-464d-af3c-e8da014483bd";
  #     fsType = "btrfs";
  #   };

  # swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
