# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

//  fileSystems."/" =
//     { device = "tmpfs";
//       fsType = "tmpfs";
//     };

//   fileSystems."/btr_pool" =
//     { device = "/dev/disk/by-uuid/08e7f0f7-eef8-4c73-a51e-692467cb83f6";
//       fsType = "btrfs";
//     };

//   fileSystems."/nix" =
//     { device = "/dev/disk/by-uuid/08e7f0f7-eef8-4c73-a51e-692467cb83f6";
//       fsType = "btrfs";
//       options = [ "subvol=@nix" ];
//     };

//   fileSystems."/persistent" =
//     { device = "/dev/disk/by-uuid/08e7f0f7-eef8-4c73-a51e-692467cb83f6";
//       fsType = "btrfs";
//       options = [ "subvol=@persistent" ];
//     };

//   fileSystems."/snapshots" =
//     { device = "/dev/disk/by-uuid/08e7f0f7-eef8-4c73-a51e-692467cb83f6";
//       fsType = "btrfs";
//       options = [ "subvol=@snapshots" ];
//     };

//   fileSystems."/tmp" =
//     { device = "/dev/disk/by-uuid/08e7f0f7-eef8-4c73-a51e-692467cb83f6";
//       fsType = "btrfs";
//       options = [ "subvol=@tmp" ];
//     };

//   fileSystems."/boot" =
//     { device = "/dev/disk/by-uuid/E795-3170";
//       fsType = "vfat";
//       options = [ "fmask=0177" "dmask=0077" ];
//     };

//   swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
